before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    binary: katapult
    main: ./cmd/katapult

dockers:
  -
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - "ghcr.io/krystal/katapult-cli:{{ .Tag }}-alpine"
      - "ghcr.io/krystal/katapult-cli:alpine"
      - "ghcr.io/krystal/katapult-cli:{{ .Tag }}"
      - "ghcr.io/krystal/katapult-cli:latest"

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  -
    name: katapult-cli
    test: system "#{bin}/katapult version"
    install: bin.install "katapult"
    commit_author:
      name: github-actions
      email: github-actions@github.com
    description: The official CLI for Katapult.
    tap:
      owner: krystal
      name: homebrew-taps
      token: "{{ .Env.KRYSTALBOT_REPO_PAT }}"
