// +build ignore

package main

import (
	"bytes"
	"io/ioutil"
	"strings"
	"text/template"
)

const start = `// Code generated by generate_holders.go; DO NOT EDIT.

package main

//go:generate go run generate_holders.go

import "github.com/krystal/go-katapult/core"

`

const holder = `type {{ . }}Holder struct {
	*core.{{ . }}
}`

var types = []string{
	"DataCentersClient", "NetworksClient",
	"OrganizationsClient", "VirtualMachinesClient",
}

func main() {
	file := start
	parts := make([]string, len(types))
	t, err := template.New("_").Parse(holder)
	if err != nil {
		panic(err)
	}
	for i, v := range types {
		buf := &bytes.Buffer{}
		if err := t.Execute(buf, v); err != nil {
			panic(err)
		}
		parts[i] = buf.String()
	}
	file += strings.Join(parts, "\n\n") + "\n"
	if err := ioutil.WriteFile("holders_generated.go", []byte(file), 0666); err != nil {
		panic(err)
	}
}
