// Code generated by generate_holders.go; DO NOT EDIT.

package main

//go:generate go run generate_holders.go

import "github.com/krystal/go-katapult/core"

type DataCentersClientHolder struct {
	*core.DataCentersClient
}

type NetworksClientHolder struct {
	*core.NetworksClient
}

type OrganizationsClientHolder struct {
	*core.OrganizationsClient
}

type VirtualMachinesClientHolder struct {
	*core.VirtualMachinesClient
}
